version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db_postgres_sdo
    image: postgres:15.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5050:5432"
    volumes:
      - ./app/init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"                         # Доступ к pgAdmin по http://localhost:8080
    volumes:
      - pgadmin_data:/var/lib/pgadmin    # Для сохранения настроек между перезапусками
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin_data:
