@host = localhost:8000
@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6InN0dWRlbnQiLCJyb2xldHlwZSI6InN0dWRlbnQiLCJzdHVkeWdyb3VwIjoiMjExLTM2NSIsImV4cCI6MTc0MzUxNTUxN30.ttfnxUpXSzZvVBo3XKnNMilmxtcresFhhWjaqHB1bik

###
# Получение данных пользователя
GET http://{{host}}/user_data
Authorization: {{token}}
Content-Type: application/json

###
# Получение статуса пользователя
GET http://{{host}}/user_status
Authorization: {{token}}
Content-Type: application/json

###
# Регистрация пользователя
POST http://{{host}}/register
Content-Type: application/json

{
    "username": "student",
    "password": "student",
    "group_name": "231-335"
}

###
# Логирование пользователя
POST http://{{host}}/login
Content-Type: application/json

{
    "username": "student",
    "password": "student"
}

###
# Получение предметов пользователя
GET http://{{host}}/subjects
Authorization: {{token}}
Content-Type: application/json

###
# Получение тасков с subject_id=1
GET http://{{host}}/tasks/1
Authorization: {{token}}
Content-Type: application/json

###
# Загрузка решения задачи в Task с ID 1
POST http://{{host}}/upload/1
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="solution.py"
Content-Type: text/x-python

inputs = input().split()  # Разделение строки на список
a1 = int(inputs[0])  # Преобразуем первое значение в число
a2 = int(inputs[1])  # Преобразуем второе значение в число
a3 = int(inputs[2])  # Преобразуем третье значение в число

b1 = a1 + a2 - a3  # Выполняем расчет для b1
b2 = b1 + a2  # Выполняем расчет для b2

print(b1, b2)  # Выводим результаты

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# Тестирование последнего загруженного решения задачи с Task ID 1
POST http://{{host}}/test/1
Authorization: {{token}}
Content-Type: application/json

###
# Получение информации о задаче с Task ID 1 и статусе решений пользователя
GET http://{{host}}/task/1
Authorization: {{token}}
Content-Type: application/json

###
GET http://{{host}}/docs
Content-Type: text/html

### Teacher
# Получение списка студентов факультета
GET http://{{host}}/api/teachers/students
Authorization: {{token}}
Content-Type: application/json

###
# Получение списка студентов по группе
GET http://{{host}}/api/teachers/groups/CS-101/students
Authorization: {{token}}
Content-Type: application/json

###
# Получение списка лабораторных работ студента
GET http://{{host}}/api/teachers/students/1/labs
Authorization: {{token}}
Content-Type: application/json

###
# Получение информации о конкретной лабораторной работе студента
GET http://{{host}}/api/teachers/students/1/labs/5
Authorization: {{token}}
Content-Type: application/json

###
# Получение списка групп факультета
GET http://{{host}}/api/teachers/groups
Authorization: {{token}}
Content-Type: application/json